remote_theme: pages-themes/hacker@v0.2.0
title: Mikis test programming portfolio
description: A beginner programmer, Mihaela Giurescu aka Miki_Dulce_Kiss_Eingel shares her test portfolio with the internet.
google_analytics: G-1EG8H88200
